### ISSUE TITLE
SSH Credentials for VirtualBox Image

### ISSUE THREAD

**Issue by c360e5f1** [RD17/ambar#1]
Hi, I was able to download the VirtualBox image for Ambar but ran into some issues configuring it and getting it to work.

I'm putting it on my server behind an Apache web server so it's hosted with a proxypass directive on a custom hostname.

However, it's trying to hit the API on port 8004 with it's IP address, which looks like it's configurable by editing the apiURL.txt file on the container.

However, I can't gain access to the container to edit the apiURL file. Easiest would be the SSH credentials.

**Comment by sochix** [comment]
Hello @pengc99!

The VM credentials is:

login - `administrator`
password - `1a2a3aambar`

To make it work you need to edit `docker-compose.local.yml`. 
* First of all, stop Ambar instance `sudo ./ambar.sh stop`
* Open `docker-compose.local.yml` and find the following:
```
 frontend:
    environment:
      api: http://192.168.56.222:8004
    image: repo.rdseventeen.com:443/ambar-frontend:latest
    ports:
    - 80:80
    restart: always
```
Replace the `http://192.168.56.222:8004` with your address.
* Start Ambar instance  `sudo ./ambar.sh start`

Hope it helps!

_P.s. we'll release docker setup very soon_
