### ISSUE TITLE
Q: Example docker-compose.yml?

### ISSUE THREAD

**Issue by noviceiii** [RD17/ambar#150]
Dear all

Can you give me a hand with the docker-compose.yml?
Sorry for that probably basic question but i struggle a bit to get docker/ ambar running again.

[1]: What other options do exist for condition?
[2]: What other parameters are allowed for restart?
[3]: What else can be given here? 
[4]: Is the crawl path the path to the local storage folder where files are located?
[5]: What is the syntax to use with spaces? Double quotes like "my folder"?
[6]: What is the meaning of volumes: source or destination folders?

(I have no need to move the source files as it is all on one single machine, and I'd keep the original files)

```
  crawler0:
    depends_on:
      serviceapi:
        condition: service_healthy [1]
    image: ambar/ambar-local-crawler
    restart: always [2]
    networks:
      - internal_network [3]
    environment:
      - apiUrl=http://serviceapi:8081
      - crawlPath=/opt/files/folder [4]
      - name=My Folder [5]
    volumes:
      -  /opt/files/folder [6]

```

Kind regards
n3
