### ISSUE TITLE
Additional Pipelines

### ISSUE THREAD

**Issue by TomKirby** [RD17/ambar#179]
Hi,

Looking at the docker compose file I can see that the following code around creating a new pipeline container seems to be structured in a way which will allow multipul pipelines to be created and distrubutue the load?

```
pipeline0:
    depends_on: 
      serviceapi: 
        condition: service_healthy                            
    image: ambar/ambar-pipeline:latest
    restart: always
    networks:
      - internal_network  
    environment:                
      - id=0
      - api_url=http://serviceapi:8081
- rabbit_host=amqp://rabbit
```

we are currently experiencing problems with large backlog within RabbitMQ of around 50,000 and it appears that the pipline is our bottleneck, could i create additional instances of the pipeline by duplicating the following code 2-3 times and chaging the name of the instance from ``pipeline0:`` to ``pipeline1:``

and also the id under the enviroment section by +1?

Regards,

Tom.
