### ISSUE TITLE
Ability to crawl recursively

### ISSUE THREAD

**Issue by 7c** [RD17/ambar#212]
I am just testing your great product. I am simply crawling /tmp like this:

``` 
 test:
    depends_on: 
      serviceapi: 
        condition: service_healthy 
    image: ambar/ambar-local-crawler
    restart: always
    networks:
      - internal_network
    expose:
      - "8082"
    environment:      
      - name=test
    volumes:
      - /tmp:/usr/data

```

is there a way to tell that it is allowed to crawl all subdirectories inside /tmp ? I have put many pdf files inside /tmp/tmp but they are not crawled but the ones at /tmp are immedieately
