### ISSUE TITLE
404 when accessing frontend

### ISSUE THREAD

**Issue by stravag** [RD17/ambar#278]
Hi

I setup the docker container according to the docker-compose example file on the web and all containers seem to start without issues.

But unfortunately I always get a 404 error when I want to access the frontend. I tried both: the pre-build images and also images I built myself from the published release 2.1.18.

```
# curl -i http://localhost:8080
HTTP/1.1 404 Not Found
X-Powered-By: Express
Vary: Origin
Access-Control-Allow-Credentials: true
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 139
Date: Thu, 12 Mar 2020 12:58:10 GMT
Connection: keep-alive

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
```

Because of the `X-Powered-By: Express` I assume this response comes from the node frontend and not the nginx.

I can't see anything suspicuous in the container logs. Except when everything is started I see periodic calls to the frontend that (according to the log) respond with a 200, not sure what is triggering that.

Any ideas?

```
➜  ambar git:(master) ✗ docker-compose up
Starting ambar_es_1     ... done
Starting ambar_db_1     ... done
Starting ambar_rabbit_1 ... done
Starting ambar_redis_1  ... done
Starting ambar_serviceapi_1 ... done
Starting ambar_webapi_1     ... done
Starting ambar_pipeline0_1  ... done
Starting ambar_frontend_1   ... done
Attaching to ambar_redis_1, ambar_rabbit_1, ambar_db_1, ambar_es_1, ambar_serviceapi_1, ambar_webapi_1, ambar_pipeline0_1, ambar_frontend_1
db_1          | 2020-03-12T12:57:05.492+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=07e88b2424f6
db_1          | 2020-03-12T12:57:05.492+0000 I CONTROL  [initandlisten] db version v3.4.2
db_1          | 2020-03-12T12:57:05.492+0000 I CONTROL  [initandlisten] git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b
db_1          | 2020-03-12T12:57:05.492+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
db_1          | 2020-03-12T12:57:05.492+0000 I CONTROL  [initandlisten] allocator: tcmalloc
db_1          | 2020-03-12T12:57:05.492+0000 I CONTROL  [initandlisten] modules: none
db_1          | 2020-03-12T12:57:05.492+0000 I CONTROL  [initandlisten] build environment:
db_1          | 2020-03-12T12:57:05.492+0000 I CONTROL  [initandlisten]     distmod: debian81
db_1          | 2020-03-12T12:57:05.492+0000 I CONTROL  [initandlisten]     distarch: x86_64
db_1          | 2020-03-12T12:57:05.492+0000 I CONTROL  [initandlisten]     target_arch: x86_64
db_1          | 2020-03-12T12:57:05.492+0000 I CONTROL  [initandlisten] options: { config: "/etc/mongod.conf", storage: { wiredTiger: { engineConfig: { cacheSizeGB: 2.0 } } } }
es_1          | [2020-03-12T12:57:08,855][INFO ][o.e.n.Node               ] [] initializing ...
pipeline0_1   | Mar 12, 2020 12:57:28 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
pipeline0_1   | WARNING: J2KImageReader not loaded. JPEG2000 files will not be processed.
pipeline0_1   | See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
pipeline0_1   | for optional dependencies.
pipeline0_1   |
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:12 ===
rabbit_1      | Starting RabbitMQ 3.6.16 on Erlang 19.2.1
rabbit_1      | Copyright (C) 2007-2018 Pivotal Software, Inc.
rabbit_1      | Licensed under the MPL.  See http://www.rabbitmq.com/
redis_1       | 1:C 12 Mar 12:57:05.409 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1       | 1:C 12 Mar 12:57:05.409 # Redis version=4.0.2, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1       | 1:C 12 Mar 12:57:05.409 # Configuration loaded
redis_1       |                 _._
redis_1       |            _.-``__ ''-._
redis_1       |       _.-``    `.  `_.  ''-._           Redis 4.0.2 (00000000/0) 64 bit
redis_1       |   .-`` .-```.  ```\/    _.,_ ''-._
redis_1       |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1       |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1       |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1       |   `-._    `-._  `-./  _.-'    _.-'
redis_1       |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1       |  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis_1       |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1       |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1       |  |    `-._`-._        _.-'_.-'    |
redis_1       |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1       |       `-._    `-.__.-'    _.-'
redis_1       |           `-._        _.-'
redis_1       |               `-.__.-'
redis_1       |
redis_1       | 1:M 12 Mar 12:57:05.410 # Server initialized
redis_1       | 1:M 12 Mar 12:57:05.411 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
db_1          | 2020-03-12T12:57:05.503+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
serviceapi_1  | [2020-03-12T12:57:22.352Z] SLAO api key must be specified
webapi_1      | [2020-03-12T12:57:28.098Z] SLAO api key must be specified
es_1          | [2020-03-12T12:57:09,053][INFO ][o.e.e.NodeEnvironment    ] [OxfHGkx] using [1] data paths, mounts [[/usr/share/elasticsearch/data (osxfs)]], net usable_space [800gb], net total_space [931.5gb], spins? [possibly], types [fuse.osxfs]
pipeline0_1   | Mar 12, 2020 12:57:28 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
pipeline0_1   | WARNING: Tesseract OCR is installed and will be automatically applied to image files unless
pipeline0_1   | you've excluded the TesseractOCRParser from the default parser.
pipeline0_1   | Tesseract may dramatically slow down content extraction (TIKA-2359).
pipeline0_1   | As of Tika 1.15 (and prior versions), Tesseract is automatically called.
pipeline0_1   | In future versions of Tika, users may need to turn the TesseractOCRParser on via TikaConfig.
rabbit_1      |
rabbit_1      |               RabbitMQ 3.6.16. Copyright (C) 2007-2018 Pivotal Software, Inc.
rabbit_1      |   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
rabbit_1      |   ##  ##
rabbit_1      |   ##########  Logs: tty
rabbit_1      |   ######  ##        tty
rabbit_1      |   ##########
rabbit_1      |               Starting broker...
redis_1       | 1:M 12 Mar 12:57:05.411 * Ready to accept connections
db_1          | 2020-03-12T12:57:05.508+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=2048M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
webapi_1      | Started on :::8080
es_1          | [2020-03-12T12:57:09,053][INFO ][o.e.e.NodeEnvironment    ] [OxfHGkx] heap size [1.9gb], compressed ordinary object pointers [true]
serviceapi_1  | Started on :::8081
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:12 ===
rabbit_1      | node           : rabbit@rabbit
rabbit_1      | home dir       : /var/lib/rabbitmq
rabbit_1      | config file(s) : /etc/rabbitmq/rabbitmq.config
rabbit_1      | cookie hash    : E4I+LiBRAYNOltJMo4M6/A==
rabbit_1      | log            : tty
rabbit_1      | sasl log       : tty
rabbit_1      | database dir   : /var/lib/rabbitmq/mnesia/rabbit@rabbit
es_1          | [2020-03-12T12:57:09,901][INFO ][o.e.n.Node               ] node name [OxfHGkx] derived from node ID [OxfHGkxITK-evU9JL63x_A]; set [node.name] to override
db_1          | 2020-03-12T12:57:06.722+0000 I CONTROL  [initandlisten]
db_1          | 2020-03-12T12:57:06.722+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
db_1          | 2020-03-12T12:57:06.722+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
db_1          | 2020-03-12T12:57:06.722+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
db_1          | 2020-03-12T12:57:06.722+0000 I CONTROL  [initandlisten]
pipeline0_1   | Mar 12, 2020 12:57:28 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
pipeline0_1   | WARNING: org.xerial's sqlite-jdbc is not loaded.
pipeline0_1   | Please provide the jar on your classpath to parse sqlite files.
pipeline0_1   | See tika-parsers/pom.xml for the correct version.
redis_1       | 1:M 12 Mar 12:57:10.532 # Possible SECURITY ATTACK detected. It looks like somebody is sending POST or Host: commands to Redis. This is likely due to an attacker attempting to use Cross Protocol Scripting to compromise your Redis instance. Connection aborted.
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | Memory high watermark set to 1575 MiB (1651539968 bytes) of 3937 MiB (4128849920 bytes) total
db_1          | 2020-03-12T12:57:06.764+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | Enabling free disk space monitoring
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | Disk free limit set to 50MB
es_1          | [2020-03-12T12:57:09,902][INFO ][o.e.n.Node               ] version[5.6.3], pid[1], build[1a2f265/2017-10-06T20:33:39.012Z], OS[Linux/4.19.76-linuxkit/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_151/25.151-b12]
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | Limiting to approx 1048476 file handles (943626 sockets)
db_1          | 2020-03-12T12:57:06.765+0000 I NETWORK  [thread1] waiting for connections on port 27017
es_1          | [2020-03-12T12:57:09,902][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Xms2g, -Xmx2g, -Des.path.home=/usr/share/elasticsearch]
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | FHC read buffering:  OFF
rabbit_1      | FHC write buffering: ON
db_1          | 2020-03-12T12:57:10.679+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48492 #1 (1 connection now open)
db_1          | 2020-03-12T12:57:10.682+0000 I -        [conn1] end connection 127.0.0.1:48492 (1 connection now open)
es_1          | [2020-03-12T12:57:11,443][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded module [aggs-matrix-stats]
es_1          | [2020-03-12T12:57:11,443][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded module [ingest-common]
es_1          | [2020-03-12T12:57:11,443][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded module [lang-expression]
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | Waiting for Mnesia tables for 30000 ms, 9 retries left
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | Waiting for Mnesia tables for 30000 ms, 9 retries left
db_1          | 2020-03-12T12:57:15.858+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48512 #2 (1 connection now open)
db_1          | 2020-03-12T12:57:15.859+0000 I -        [conn2] end connection 127.0.0.1:48512 (1 connection now open)
es_1          | [2020-03-12T12:57:11,444][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded module [lang-groovy]
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | Priority queues enabled, real BQ is rabbit_variable_queue
db_1          | 2020-03-12T12:57:21.039+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48536 #3 (1 connection now open)
db_1          | 2020-03-12T12:57:21.039+0000 I -        [conn3] end connection 127.0.0.1:48536 (1 connection now open)
es_1          | [2020-03-12T12:57:11,444][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded module [lang-mustache]
db_1          | 2020-03-12T12:57:22.585+0000 I NETWORK  [thread1] connection accepted from 172.19.0.6:37560 #4 (1 connection now open)
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | Starting rabbit_node_monitor
es_1          | [2020-03-12T12:57:11,444][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded module [lang-painless]
es_1          | [2020-03-12T12:57:11,444][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded module [parent-join]
db_1          | 2020-03-12T12:57:22.620+0000 I NETWORK  [conn4] received client metadata from 172.19.0.6:37560 conn4: { driver: { name: "nodejs", version: "2.2.36" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.19.76-linuxkit" }, platform: "Node.js v8.10.0, LE, mongodb-core: 2.1.20" }
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | Management plugin: using rates mode 'basic'
es_1          | [2020-03-12T12:57:11,444][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded module [percolator]
es_1          | [2020-03-12T12:57:11,444][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded module [reindex]
db_1          | 2020-03-12T12:57:26.157+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48546 #5 (2 connections now open)
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | msg_store_transient: using rabbit_msg_store_ets_index to provide index
es_1          | [2020-03-12T12:57:11,444][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded module [transport-netty3]
db_1          | 2020-03-12T12:57:26.157+0000 I -        [conn5] end connection 127.0.0.1:48546 (2 connections now open)
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | msg_store_persistent: using rabbit_msg_store_ets_index to provide index
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | started TCP Listener on [::]:5672
es_1          | [2020-03-12T12:57:11,444][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded module [transport-netty4]
db_1          | 2020-03-12T12:57:28.325+0000 I NETWORK  [thread1] connection accepted from 172.19.0.7:47936 #6 (2 connections now open)
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | Management plugin started. Port: 15672
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | Statistics database started.
es_1          | [2020-03-12T12:57:11,445][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded plugin [analysis-morphology]
es_1          | [2020-03-12T12:57:11,445][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded plugin [analysis-smartcn]
es_1          | [2020-03-12T12:57:11,445][INFO ][o.e.p.PluginsService     ] [OxfHGkx] loaded plugin [analysis-stempel]
db_1          | 2020-03-12T12:57:28.362+0000 I NETWORK  [conn6] received client metadata from 172.19.0.7:47936 conn6: { driver: { name: "nodejs", version: "2.2.36" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.19.76-linuxkit" }, platform: "Node.js v8.10.0, LE, mongodb-core: 2.1.20" }
rabbit_1      |  completed with 6 plugins.
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:17 ===
rabbit_1      | Server startup complete; 6 plugins started.
rabbit_1      |  * rabbitmq_management
rabbit_1      |  * rabbitmq_web_dispatch
rabbit_1      |  * rabbitmq_management_agent
rabbit_1      |  * amqp_client
rabbit_1      |  * cowboy
rabbit_1      |  * cowlib
es_1          | [2020-03-12T12:57:13,869][INFO ][o.e.d.DiscoveryModule    ] [OxfHGkx] using discovery type [zen]
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:22 ===
rabbit_1      | accepting AMQP connection <0.498.0> (172.19.0.6:48574 -> 172.19.0.4:5672)
db_1          | 2020-03-12T12:57:31.281+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48582 #7 (3 connections now open)
es_1          | [2020-03-12T12:57:14,851][INFO ][o.e.n.Node               ] initialized
es_1          | [2020-03-12T12:57:14,851][INFO ][o.e.n.Node               ] [OxfHGkx] starting ...
db_1          | 2020-03-12T12:57:31.281+0000 I -        [conn7] end connection 127.0.0.1:48582 (3 connections now open)
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:22 ===
rabbit_1      | connection <0.498.0> (172.19.0.6:48574 -> 172.19.0.4:5672): user 'guest' authenticated and granted access to vhost '/'
es_1          | [2020-03-12T12:57:15,096][INFO ][o.e.t.TransportService   ] [OxfHGkx] publish_address {172.19.0.5:9300}, bound_addresses {0.0.0.0:9300}
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:28 ===
rabbit_1      | accepting AMQP connection <0.523.0> (172.19.0.7:58112 -> 172.19.0.4:5672)
es_1          | [2020-03-12T12:57:15,096][INFO ][o.e.b.BootstrapChecks    ] [OxfHGkx] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:28 ===
rabbit_1      | connection <0.523.0> (172.19.0.7:58112 -> 172.19.0.4:5672): user 'guest' authenticated and granted access to vhost '/'
es_1          | [2020-03-12T12:57:18,192][INFO ][o.e.c.s.ClusterService   ] [OxfHGkx] new_master {OxfHGkx}{OxfHGkxITK-evU9JL63x_A}{NQ2dlj_4TY6o3hp7pPoaFg}{172.19.0.5}{172.19.0.5:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
es_1          | [2020-03-12T12:57:18,234][INFO ][o.e.h.n.Netty4HttpServerTransport] [OxfHGkx] publish_address {172.19.0.5:9200}, bound_addresses {0.0.0.0:9200}
es_1          | [2020-03-12T12:57:18,234][INFO ][o.e.n.Node               ] [OxfHGkx] started
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:28 ===
rabbit_1      | accepting AMQP connection <0.528.0> (172.19.0.8:56526 -> 172.19.0.4:5672)
es_1          | [2020-03-12T12:57:18,825][INFO ][o.e.g.GatewayService     ] [OxfHGkx] recovered [2] indices into cluster_state
rabbit_1      |
rabbit_1      | =INFO REPORT==== 12-Mar-2020::12:57:28 ===
rabbit_1      | connection <0.528.0> (172.19.0.8:56526 -> 172.19.0.4:5672): user 'guest' authenticated and granted access to vhost '/'
es_1          | [2020-03-12T12:57:20,788][INFO ][o.e.c.r.a.AllocationService] [OxfHGkx] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[ambar_log_record_data][0]] ...]).
db_1          | 2020-03-12T12:57:36.401+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48594 #8 (3 connections now open)
db_1          | 2020-03-12T12:57:36.402+0000 I -        [conn8] end connection 127.0.0.1:48594 (3 connections now open)
frontend_1    | 127.0.0.1 - - [12/Mar/2020:12:57:37 +0000] "GET / HTTP/1.1" 200 969 "-" "curl/7.52.1" "-"
db_1          | 2020-03-12T12:57:41.524+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48608 #9 (3 connections now open)
db_1          | 2020-03-12T12:57:41.524+0000 I -        [conn9] end connection 127.0.0.1:48608 (3 connections now open)
frontend_1    | 127.0.0.1 - - [12/Mar/2020:12:57:42 +0000] "GET / HTTP/1.1" 200 969 "-" "curl/7.52.1" "-"
db_1          | 2020-03-12T12:57:46.613+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48622 #10 (3 connections now open)
db_1          | 2020-03-12T12:57:46.613+0000 I -        [conn10] end connection 127.0.0.1:48622 (3 connections now open)
frontend_1    | 127.0.0.1 - - [12/Mar/2020:12:57:47 +0000] "GET / HTTP/1.1" 200 969 "-" "curl/7.52.1" "-"
db_1          | 2020-03-12T12:57:51.737+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48636 #11 (3 connections now open)
db_1          | 2020-03-12T12:57:51.737+0000 I -        [conn11] end connection 127.0.0.1:48636 (3 connections now open)
frontend_1    | 127.0.0.1 - - [12/Mar/2020:12:57:53 +0000] "GET / HTTP/1.1" 200 969 "-" "curl/7.52.1" "-"
db_1          | 2020-03-12T12:57:56.856+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48650 #12 (3 connections now open)
db_1          | 2020-03-12T12:57:56.856+0000 I -        [conn12] end connection 127.0.0.1:48650 (3 connections now open)
frontend_1    | 127.0.0.1 - - [12/Mar/2020:12:57:58 +0000] "GET / HTTP/1.1" 200 969 "-" "curl/7.52.1" "-"
db_1          | 2020-03-12T12:58:01.967+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48668 #13 (3 connections now open)
db_1          | 2020-03-12T12:58:01.967+0000 I -        [conn13] end connection 127.0.0.1:48668 (3 connections now open)
frontend_1    | 127.0.0.1 - - [12/Mar/2020:12:58:03 +0000] "GET / HTTP/1.1" 200 969 "-" "curl/7.52.1" "-"
db_1          | 2020-03-12T12:58:07.083+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48682 #14 (3 connections now open)
db_1          | 2020-03-12T12:58:07.083+0000 I -        [conn14] end connection 127.0.0.1:48682 (3 connections now open)
frontend_1    | 127.0.0.1 - - [12/Mar/2020:12:58:08 +0000] "GET / HTTP/1.1" 200 969 "-" "curl/7.52.1" "-"
db_1          | 2020-03-12T12:58:12.205+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:48700 #15 (3 connections now open)
db_1          | 2020-03-12T12:58:12.205+0000 I -        [conn15] end connection 127.0.0.1:48700 (3 connections now open)
redis_1       | 1:M 12 Mar 12:58:12.310 # Possible SECURITY ATTACK detected. It looks like somebody is sending POST or Host: commands to Redis. This is likely due to an attacker attempting to use Cross Protocol Scripting to compromise your Redis instance. Connection aborted.
frontend_1    | 127.0.0.1 - - [12/Mar/2020:12:58:13 +0000] "GET / HTTP/1.1" 200 969 "-" "curl/7.52.1" "-"
```

**Comment by sochix** [comment]
@stravag please attach your docker-compose file

**Comment by stravag** [comment]
```
version: "2.1"
networks:
  internal_network:
services:      
  db:
    restart: always
    networks:
      - internal_network
    image: repo.ambar.cloud/ambar-mongodb:2.1
    environment:
      - cacheSizeGB=2
    volumes:
      - /usr/local/opt/ambar/db:/data/db
    expose:
      - "27017"   
  es:
    restart: always
    networks:
      - internal_network
    image: repo.ambar.cloud/ambar-es:2.1
    expose:
      - "9200" 
    environment:
      - cluster.name=ambar-es
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1  
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /usr/local/opt/ambar/es:/usr/share/elasticsearch/data
  rabbit:
    restart: always
    networks:
      - internal_network
    image: repo.ambar.cloud/ambar-rabbit:2.1
    hostname: rabbit
    expose:
      - "15672"
      - "5672"   
    volumes:
      - /usr/local/opt/ambar/rabbit:/var/lib/rabbitmq
  redis:
    restart: always
    sysctls:
      - net.core.somaxconn=1024
    networks:
      - internal_network
    image: repo.ambar.cloud/ambar-redis:2.1
    expose:
      - "6379" 
  serviceapi:
    depends_on:
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      es:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: always
    networks:
      - internal_network
    image: repo.ambar.cloud/ambar-serviceapi:2.1
    expose:
      - "8081"  
    environment:            
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - rabbitHost=amqp://rabbit
      - langAnalyzer=ambar_de
  webapi:
    depends_on:
      serviceapi:
        condition: service_healthy
    restart: always
    networks:
      - internal_network
    image: repo.ambar.cloud/ambar-webapi:2.1
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - uiLang=en
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - serviceApiUrl=http://serviceapi:8081
      - rabbitHost=amqp://rabbit
  frontend:
    depends_on:
      webapi:
        condition: service_healthy
    image: repo.ambar.cloud/ambar-frontend:2.1
    restart: always
    networks:
      - internal_network
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      - api=http://localhost:8080
  pipeline0:
    depends_on: 
      serviceapi: 
        condition: service_healthy                            
    image: repo.ambar.cloud/ambar-pipeline:2.1
    restart: always
    networks:
      - internal_network  
    environment:                
      - id=0
      - api_url=http://serviceapi:8081
      - rabbit_host=amqp://rabbit
#  ${crawlerName}:
#    depends_on:
#      serviceapi:
#        condition: service_healthy
#    image: repo.ambar.cloud:443/ambar-local-crawler:2.1
#    restart: always
#    networks:
#      - internal_network
#    expose:
#      - "8082"
#    environment:
#      - name=${crawlerName}
#    volumes:
#      - ${pathToCrawl}:/usr/data
```
