### ISSUE TITLE
How to Build Docker Containers

### ISSUE THREAD

**Issue by ark-** [RD17/ambar#284]
Hi. I had to work through multiple issues and the source code to get it working in my instance so I would like to pay it forward.

## Build

 1. `git clone https://github.com/RD17/ambar.git`
 2. `cd ~/ambar/FrontEnd` 
 3. If compiling this on a different machine than what you're deploying on then before performing compile `export PORT={YOUR_WEB_FRONTEND_PORT)` and `export FRONTEND_HOST={YOUR_HOST_IP}`. I used `80` and `192.168.1.1`.
 3. `node npm install`
 4.  `npm run compile`
 5. `docker build . -t frontend`
 6. `cd ~/ambar/WebApi`
 7. `docker build . -t webapi`
 8. `cd ~/ambar/ServiceApi`
 9. `docker build . -t serviceapi`
 10. `cd ~/ambar/Redis`
 11. `docker build . -t redis`
 12. `cd ~/ambar/Rabbit`
 13. `docker build . -t rabbit`
 14. `cd ~/ambar/Pipeline`
 15. `docker build . -t pipeline0`
 16. `cd ~/ambar/LocalCrawler`
 17. `docker build . -t localcrawler`
 18. `cd ~/ambar/MongoDB`
 19. `docker build . -t mongodb`
 20. `cd ~/ambar/ElasticSearch`
 21. `docker build . -t elasticsearch`
 22. Set elasticsearch docker host settings, these are referenced [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_set_vm_max_map_count_to_at_least_262144)

```
sysctl -w vm.max_map_count=262144
sysctl -w net.ipv4.ip_local_port_range="15000 61000"
sysctl -w net.ipv4.tcp_fin_timeout=30
sysctl -w net.core.somaxconn=1024
sysctl -w net.core.netdev_max_backlog=2000
sysctl -w net.ipv4.tcp_max_syn_backlog=2048
sysctl -w vm.overcommit_memory=1
```

## Docker Compose

My final docker compose:

``` yml
version: "2.1"
networks:
  internal_network:
services:      
  db:
    restart: always
    networks:
      - internal_network
    build: ./MongoDB
    environment:
      - cacheSizeGB=2
    volumes:
      - ~/ambar/mapped_vols/db:/data/db
    expose:
      - "27017"   
  es:
    restart: always
    networks:
      - internal_network
    build: ./ElasticSearch
    expose:
      - "9200" 
    environment:
      - cluster.name=ambar-es
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - max_map_count=262144
    ulimits:
      memlock:
        soft: -1
        hard: -1  
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ~/ambar/mapped_vols/es:/usr/share/elasticsearch/data
  rabbit:
    restart: always
    networks:
      - internal_network
    build: ./Rabbit
    hostname: rabbit
    expose:
      - "15672"
      - "5672"   
    volumes:
      - ~/ambar/mapped_vols/rabbit:/var/lib/rabbitmq
  redis:
    restart: always
    sysctls:
      - net.core.somaxconn=1024
    networks:
      - internal_network
    build: ./Redis
    expose:
      - "6379" 
  serviceapi:
    depends_on:
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      es:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: always
    networks:
      - internal_network
    build: ./ServiceApi
    expose:
      - "8081"  
    ports:
      - "8081:8081"
    environment:            
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - rabbitHost=amqp://rabbit
      - langAnalyzer=ambar_en
  webapi:
    depends_on:
      serviceapi:
        condition: service_healthy
    restart: always
    networks:
      - internal_network
    build: ./WebApi
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:            
      - uiLang=en
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - serviceApiUrl=http://serviceapi:8081
      - rabbitHost=amqp://rabbit  
  frontend:
    depends_on:
      webapi:
        condition: service_healthy
    build: ./FrontEnd
    restart: always
    networks:
      - internal_network
    ports:
      - "82:80"
    expose:
      - "82"
    environment:
      - api=http://192.168.1.1:8080  
  pipeline0:
    depends_on: 
      serviceapi: 
        condition: service_healthy                            
    build: ./Pipeline
    restart: always
    networks:
      - internal_network  
    environment:                
      - id=0
      - api_url=http://serviceapi:8081
      - rabbit_host=amqp://rabbit
  my-docs:
    depends_on: 
      serviceapi: 
        condition: service_healthy 
    build: ./LocalCrawler
    restart: always
    networks:
      - internal_network
    expose:
      - "8082"
    environment:      
      - name=my-docs
      - apiUrl=http://serviceapi:8081
    volumes:
      - ~/Documents:/usr/data
```

The differences between my `docker-compose.yml` and those listed [https://ambar.cloud/docs/installation-docker/](https://ambar.cloud/docs/installation-docker/) are:

- I performed the modifications suggested on [this page](https://ambar.cloud/docs/installation-docker/).
- I switched `image` attributes to `build` as I have built these locally
- I added `- max_map_count=262144` to elasticsearch environment
- I changed the external `frontend` port to 82 as per step 3 above
- I added `- apiUrl=http://serviceapi:8081` to the crawler as it was polling the wrong port without this

 Finally, to get it going:
``` bash
cd ~/ambarr && docker-compose up -d
```
