### ISSUE TITLE
Bug: Fresh install, going to server IP redirects me to "https://frontend" 

### ISSUE THREAD

**Issue by hbh7** [RD17/ambar#57]
Hey all. I tried to freshly install this using the directions and the ambar.py script. Running Ubuntu Server 17.04. Initially it said ambar running on http://:80 but putting in the IP into the config under fe and host gets it to say http://i.p.i.p:80 but still no change. 

Anyone have any ideas what I might be doing wrong? I can provide any more info needed.

Thanks,
hbh7

**Comment by hbh7** [comment]
Just set up a brand new Ubuntu 16.04 VM, and it did the exact same thing. "Ambar is running on http://10.20.31.108:80" but if i go to that IP, it brings me right to "https://frontend"

https://blog.ambar.cloud/ambar-installation-step-by-step-guide-2/ These are the directions I followed btw

**Comment by sochix** [comment]
@hbh7 can you post your `config.json` here?

**Comment by hbh7** [comment]
```
{
    "db": {
        "cacheSizeGb": 2
    },
    "dockerComposeTemplate": "https://static.ambar.cloud/docker-compose.template.yml",
    "dockerRepo": "ambar",
    "dataPath": "/opt/ambar",
    "ocr": {
        "pdfMaxPageCount": 5000,
        "pdfSymbolsPerPageThreshold": 100
    },
    "fe": {
        "external": {
            "protocol": "http",
            "host": "10.20.31.108",
            "port": "80"
        }
    },
    "dropbox": {
        "redirectUri": "",
        "clientId": ""
    },
    "es": {
        "heapSize": "1g",
        "containerSize": "2g"
    },
    "api": {
        "auth": "basic",
        "pipelineCount": 1,
        "showFilePreview": "false",
        "external": {
            "protocol": "http",
            "host": "10.20.31.108",
            "port": "80"
        },
        "analyticsToken": "cda4b0bb11a1f32aed7564b08c455992",
        "crawlerCount": 1,
        "cacheSize": "1g",
        "defaultLangAnalyzer": "ambar_en",
        "mode": "ce"
    }
```

**Comment by hbh7** [comment]
Anyone have any ideas? Would really love to get this working. Thanks

**Comment by isido993** [comment]
Hi @hbh7 

Please run:
`sudo docker exec -i -t ambar_proxy_1 /bin/bash`
 `cat /etc/nginx/conf.d/default.conf`
and post the result here.

Thanks.

**Comment by hbh7** [comment]
```
root@4c444dbbbbeb:/# cat /etc/nginx/conf.d/default.conf
server {
  listen 80;
  server_name ambar-fe;
  client_max_body_size 1024m;
  location /api/ {
    proxy_pass http://webapi:8080/api/;
  }
  location / {
    proxy_pass http://frontend:80/;
  }
}
```

**Comment by isido993** [comment]
@hbh7 this seems ok. Let's go further, please also post your docker-compose.yml file.

**Comment by hbh7** [comment]
Sure
```
hbh7@VM-Ambar:~$ cat docker-compose.yml
version: "2"
networks:
  internal_network:
services:
  webapi:
    restart: always
    networks:
      - internal_network
    image: ambar/ambar-webapi:latest
    expose:
      - "8080"
    environment:
      - dockerRepo=ambar
      - db=mongodb://db:27017/ambar_data
      - fe=http://10.20.31.103:80
      - api=http://webapi:8080
      - es=http://es:9200
      - redis=webapi-cache
      - rabbit=amqp://rabbit
      - mode=ce
      - pipelineCount=1
      - crawlerCount=1
      - dropboxClientId=
      - dropboxRedirectUri=
      - defaultLangAnalyzer=ambar_en
      - analyticsToken=cda4b0bb11a1f32aed7564b08c455992
      - auth=basic
      - ocrPdfMaxPageCount=5000
      - ocrPdfSymbolsPerPageThreshold=100
      - showFilePreview=false
    depends_on:
      - db
      - es
      - webapi-cache
      - proxy
      - rabbit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  webapi-cache:
    restart: always
    image: redis:alpine
    networks:
      - internal_network
    expose:
      - "6379"
    ports:
      - "6379:6379"
    mem_limit: 1g
  proxy:
    image: ambar/ambar-proxy:latest
    networks:
      - internal_network
    restart: always
    environment:
      - API_EXT_PORT=80
      - FE_EXT_PORT=80
    expose:
      - 80

    ports:
      - "80:80"

  frontend:
    image: ambar/ambar-frontend:latest
    networks:
      - internal_network
    depends_on:
      - webapi
    expose:
      - "80"
    restart: always
    environment:
      - api=http://:80
  db:
    restart: always
    image: ambar/ambar-mongodb:latest
    networks:
      - internal_network
    environment:
      - cacheSizeGB=2
    volumes:
      - /opt/ambar/db:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"
  es:
    image: ambar/ambar-es:latest
    networks:
      - internal_network
    restart: always
    expose:
      - "9200"
    ports:
      - "9200:9200"
    environment:
      - cluster.name=ambar-es
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - security.manager.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/ambar/es:/usr/share/elasticsearch/data
  rabbit:
    image: ambar/ambar-rabbit:latest
    networks:
      - internal_network
    hostname: rabbit
    expose:
      - "15672"
      - "5672"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /opt/ambar/rabbit:/var/lib/rabbitmq
```

**Comment by isido993** [comment]
Ok, now:
`wget -O ambar.py https://static.ambar.cloud/ambar.py && chmod +x ./ambar.py`
`sudo ./ambar.py update`
And `cat docker-compose.yml` again
Thnx

**Comment by hbh7** [comment]
Sure. 

Not sure if this is relevant or not, but saw this and thought it odd. This is an excerpt from the script running the update. 
```
...
Stopping Ambar...
"docker rm" requires at least 1 argument(s).
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
Crawlers containers removed
"docker rm" requires at least 1 argument(s).
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
Pipeline containers removed
Stopping ambar_frontend_1     ... done
...
```

And here's the docker compose file after startup finished. 
```
hbh7@VM-Ambar:~$ cat docker-compose.yml  
version: "2"
networks:
  internal_network:
services:
  webapi:
    restart: always
    networks:
      - internal_network
    image: ambar/ambar-webapi:latest
    expose:
      - "8080"
    environment:
      - dockerRepo=ambar
      - db=mongodb://db:27017/ambar_data
      - fe=http://10.20.31.103:80
      - api=http://webapi:8080
      - es=http://es:9200
      - redis=webapi-cache
      - rabbit=amqp://rabbit
      - mode=ce
      - pipelineCount=1
      - crawlerCount=1
      - dropboxClientId=
      - dropboxRedirectUri=
      - defaultLangAnalyzer=ambar_en
      - analyticsToken=cda4b0bb11a1f32aed7564b08c455992
    networks:
      - internal_network
    environment:
      - cacheSizeGB=2
    volumes:
      - /opt/ambar/db:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"
  es:
    image: ambar/ambar-es:latest
    networks:
      - internal_network
    restart: always
    expose:
      - "9200"
    ports:
      - "9200:9200"
    environment:
      - cluster.name=ambar-es
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - security.manager.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/ambar/es:/usr/share/elasticsearch/data
  rabbit:
    image: ambar/ambar-rabbit:latest
    networks:
      - internal_network
    hostname: rabbit
    expose:
      - "15672"
      - "5672"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /opt/ambar/rabbit:/var/lib/rabbitmq
```

**Comment by isido993** [comment]
@hbh7 thnaks, but you posted not the entire `docker-compose.yml`, please repost the missing part.
Also please `sudo docker ps -a` and post the result.

**Comment by hbh7** [comment]
My apologies, I'm on a phone on my way to work so it's a bit difficult lol

```
version: "2"
networks:
  internal_network:
services:
  webapi:
    restart: always
    networks:
      - internal_network
    image: ambar/ambar-webapi:latest
    expose:
      - "8080"
    environment:
      - dockerRepo=ambar
      - db=mongodb://db:27017/ambar_data
      - fe=http://10.20.31.103:80
      - api=http://webapi:8080
      - es=http://es:9200
      - redis=webapi-cache
      - rabbit=amqp://rabbit
      - mode=ce
      - pipelineCount=1
      - crawlerCount=1
      - dropboxClientId=
      - dropboxRedirectUri=
      - defaultLangAnalyzer=ambar_en
      - analyticsToken=cda4b0bb11a1f32aed7564b08c455992
      - auth=basic
      - ocrPdfMaxPageCount=5000
      - ocrPdfSymbolsPerPageThreshold=100
      - showFilePreview=false
    depends_on:
      - db
      - es
      - webapi-cache
      - proxy
      - rabbit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  webapi-cache:
    restart: always
    image: redis:alpine   
    networks:
      - internal_network    
    expose:
      - "6379"
    ports:
      - "6379:6379" 
    mem_limit: 1g 
  proxy:
    image: ambar/ambar-proxy:latest
    networks:
      - internal_network
    restart: always
    environment:
      - API_EXT_PORT=80
      - FE_EXT_PORT=80
    expose:
      - 80
      
    ports:
      - "80:80"
      
  frontend:
    image: ambar/ambar-frontend:latest
    networks:
      - internal_network
    depends_on:
      - webapi
    expose:
      - "80"
    restart: always
    environment:
      - api=http://:80
  db:
    restart: always
    image: ambar/ambar-mongodb:latest
    networks:
      - internal_network
    environment:
      - cacheSizeGB=2
    volumes:
      - /opt/ambar/db:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"
  es:
    image: ambar/ambar-es:latest
    networks:
      - internal_network
    restart: always
    expose:
      - "9200"
    ports:
      - "9200:9200"
    environment:
      - cluster.name=ambar-es
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - security.manager.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1  
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/ambar/es:/usr/share/elasticsearch/data
  rabbit:
    image: ambar/ambar-rabbit:latest
    networks:
      - internal_network
    hostname: rabbit
    expose:
      - "15672"
      - "5672"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /opt/ambar/rabbit:/var/lib/rabbitmq
```

Here's the docker command 
```
:
docker-compose.yml                         100% 2611     2.7MB/s   00:00
hbh7@VM-Ambar:~$ sudo docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                   PORTS                                                                                        NAMES
4a38a83bbbfc        ambar/ambar-frontend:latest   "/bin/sh -c 'echo ..."   11 minutes ago      Up 11 minutes            80/tcp                                                                                       ambar_frontend_1
7f7caad4e8b3        ambar/ambar-webapi:latest     "/bin/sh -c 'docke..."   12 minutes ago      Up About a minute        8080/tcp                                                                                     ambar_webapi_1
35fedce49484        redis:alpine                  "docker-entrypoint..."   12 minutes ago      Up 12 minutes            0.0.0.0:6379->6379/tcp                                                                       ambar_webapi-cache_1
d46dce8ed110        ambar/ambar-rabbit:latest     "docker-entrypoint..."   12 minutes ago      Up 12 minutes            4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   ambar_rabbit_1
718e233e3523        ambar/ambar-proxy:latest      "/entrypoint.sh"         12 minutes ago      Up 12 minutes            0.0.0.0:80->80/tcp                                                                           ambar_proxy_1
f2a9cf8a6506        ambar/ambar-mongodb:latest    "/entrypoint.sh"         12 minutes ago      Up 12 minutes            0.0.0.0:27017->27017/tcp                                                                     ambar_db_1
e675b409a34d        ambar/ambar-es:latest         "/docker-entrypoin..."   12 minutes ago      Up 12 minutes            0.0.0.0:9200->9200/tcp, 9300/tcp                                                             ambar_es_1
e828ddb0b736        hello-world                   "/hello"                 12 days ago         Exited (0) 12 days ago                                                                                                brave_kalam
e1186524def2        hello-world                   "/hello"                 12 days ago         Exited (0) 12 days ago                                                                                                vigilant_roentgen
```
